# Generated by Django 3.2.7 on 2022-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_author_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
